# Generated by Django 3.1.2 on 2020-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('min_customer', models.CharField(max_length=8)),
                ('max_customer', models.CharField(max_length=8)),
                ('avg_sales', models.CharField(max_length=8)),
                ('manager', models.CharField(max_length=25)),
            ],
        ),
    ]
