# Generated by Django 3.1.2 on 2020-10-17 22:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salmon_cookies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='manager',
            field=models.CharField(max_length=25, verbose_name=django.contrib.auth.models.User),
        ),
    ]
