# Generated by Django 3.1.2 on 2020-10-17 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salmon_cookies', '0003_auto_20201017_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='manager',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
